server:
  port: 8081
  servlet:
    session:
      cookie:
        name: UISESSION
  
security:
  oauth2:
    client:
      client-id: bse
      client-secret: 123
      access-token-uri: https://localhost:8083/oauth/token
      user-authorization-uri: https://localhost:8083/oauth/authorize
      pre-established-redirect-uri: http://localhost:8081/token-handler
      use-current-uri: false
    resource:
      token-info-uri: https://localhost:8083/oauth/check_token
      user-info-uri: https://localhost:8083/user/me
