server:
  port: 8084
  servlet:
    session:
      cookie:
        name: UISESSION
  
security:
  oauth2:
    client:
      client-id: sipas
      client-secret: 123
    resource:
      token-info-uri: https://localhost:8083/oauth/check_token
      user-info-uri: https://localhost:8083/user/me
